/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peluchitosstoreui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Peluchito;

/**
 *
 * @author escoo
 */
public class Buscar extends javax.swing.JFrame {

    ArrayList<Peluchito> listaPeluches = new ArrayList<Peluchito>();

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    Buscar(ArrayList<Peluchito> listaPeluches) {
        this.listaPeluches = listaPeluches;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        referenciaLabel = new javax.swing.JLabel();
        tamanoLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreLabel.setText("Nombre:");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        referenciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        referenciaLabel.setText("--");

        tamanoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanoLabel.setText("--");

        cantidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadLabel.setText("--");

        precioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioLabel.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(referenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamanoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(buscarButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buscarButton)
                .addGap(18, 18, 18)
                .addComponent(referenciaLabel)
                .addGap(18, 18, 18)
                .addComponent(tamanoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidadLabel)
                .addGap(10, 10, 10)
                .addComponent(precioLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String nombre = nombreTextField.getText();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe digitar el nombre del peluche");
        } else {
            String dbURL = "jdbc:mysql://localhost:3306/peluchitosstore";
            String username = "root";
            String password = "123456";
            try {
                Connection conn = DriverManager.getConnection(dbURL, username, password);

                String sql = "SELECT * FROM peluchitos WHERE nombre = '" + nombre + "'";
                Statement statement = conn.createStatement();

                ResultSet result = statement.executeQuery(sql);

                if (result.next()) {
                    referenciaLabel.setText("Referencia: " + result.getString(2));
                    precioLabel.setText(String.valueOf("Precio: " + result.getDouble(4)));
                    cantidadLabel.setText(String.valueOf("Cantidad: " + result.getInt(5)));
                    tamanoLabel.setText("Tamaño: " + result.getString(6));
                } else {
                    JOptionPane.showMessageDialog(null, "Peluche no encontrado");
                }

                conn.close();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

        /*    boolean existePeluche = false;
        for (int i = 0; i < listaPeluches.size(); i++) {
            if (nombre.equals(listaPeluches.get(i).getNombre())) {
                referenciaLabel.setText("Referencia: " + listaPeluches.get(i).getReferencia());
                precioLabel.setText(String.valueOf("Precio: " + listaPeluches.get(i).getPrecio()));
                cantidadLabel.setText(String.valueOf("Cantidad: " + listaPeluches.get(i).getCantidad()));
                tamanoLabel.setText("Tamaño: " + listaPeluches.get(i).getTamano());
                existePeluche = true;
            }
        }
        if (!existePeluche)
            JOptionPane.showMessageDialog(null, "Peluche no encontrado");*/
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel referenciaLabel;
    private javax.swing.JLabel tamanoLabel;
    // End of variables declaration//GEN-END:variables
}
